BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Url] (
    [id] INT NOT NULL IDENTITY(1,1),
    [originalUrl] NVARCHAR(1000) NOT NULL,
    [shortCode] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Url_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Url_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Url_shortCode_key] UNIQUE NONCLUSTERED ([shortCode])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
